# Importing necessary libraries

In [1]:
import pandas as pd

# Getting the dataset

In [2]:
df = pd.read_csv('atp_tennis.csv')

In [3]:
df.head()

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,63,77,-1,-1,-1.0,-1.0,6-4 6-2
1,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,56,5,-1,-1,-1.0,-1.0,3-6 3-6
2,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Escude N.,Baccanello P.,Escude N.,40,655,-1,-1,-1.0,-1.0,6-7 7-5 6-3
3,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Knippschild J.,Federer R.,Federer R.,87,65,-1,-1,-1.0,-1.0,1-6 4-6
4,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Fromberg R.,Woodbridge T.,Fromberg R.,81,198,-1,-1,-1.0,-1.0,7-6 5-7 6-4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65704 entries, 0 to 65703
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  65704 non-null  object
 1   Date        65704 non-null  object
 2   Series      65704 non-null  object
 3   Court       65704 non-null  object
 4   Surface     65704 non-null  object
 5   Round       65704 non-null  object
 6   Best of     65704 non-null  int64
 7   Player_1    65704 non-null  object
 8   Player_2    65704 non-null  object
 9   Winner      65704 non-null  object
 10  Rank_1      65704 non-null  int64
 11  Rank_2      65704 non-null  int64
 12  Pts_1       65704 non-null  int64
 13  Pts_2       65704 non-null  int64
 14  Odd_1       65704 non-null  float64
 15  Odd_2       65704 non-null  float64
 16  Score       65704 non-null  object
dtypes: float64(2), int64(5), object(10)
memory usage: 8.5+ MB

In [5]:
df.shape

(65704, 17)

# Data Cleaning

In [6]:
# Seeing number of null values
df.isnull().sum()

Tournament    0
Date          0
Series        0
Court         0
Surface       0
Round         0
Best of       0
Player_1      0
Player_2      0
Winner        0
Rank_1        0
Rank_2        0
Pts_1         0
Pts_2         0
Odd_1         0
Odd_2         0
Score         0
dtype: int64

**There are no null values in the dataset**

In [7]:
# Converting feature Date from datatype object to datatype date
df['Date'] = pd.to_datetime(df['Date'])

In [8]:
# Categorical columns
cat_col = [col for col in df.columns if df[col].dtype == 'object']
print('Categorical columns :',cat_col)
# Numerical columns
num_col = [col for col in df.columns if df[col].dtype != 'object']
print('Numerical columns :',num_col)

Categorical columns : ['Tournament', 'Series', 'Court', 'Surface', 'Round', 'Player_1', 'Player_2', 'Winner', 'Score']
Numerical columns : ['Date', 'Best of', 'Rank_1', 'Rank_2', 'Pts_1', 'Pts_2', 'Odd_1', 'Odd_2']

In [9]:
list(df['Player_1'].unique())

['Dosedel S.',
 'Clement A.',
 'Escude N.',
 'Knippschild J.',
 'Fromberg R.',
 'Arthurs W.',
 'Grosjean S.',
 'Balcells J.',
 'Hewitt L.',
 'Tebbutt M.',
 'Martin A.',
 'Draper S.',
 'Petrovic D.',
 'Pozzi G.',
 'Stoltenberg J.',
 'Goldstein P.',
 'Enqvist T.',
 'Lisnard J.',
 'Sekulov J.',
 'Norman M.',
 'Vinck C.',
 'Henman T.',
 'Kumar S.',
 'Behrend T.',
 'Rochus C.',
 'Delgado J.',
 'Spottl M.',
 'Hantschk M.',
 'Kroslak J.',
 'Ketola T.',
 'Zib T.',
 'Paes L.',
 'Ram A.',
 'Sanguinetti D.',
 'Kilderry P.',
 'Tabara M.',
 'Ishii Y.',
 'Vinciguerra A.',
 'Agenor R.',
 'Jonsson F.',
 'Vanek J.',
 'Manta L.',
 'Golmard J.',
 'Pioline C.',
 'Damm M.',
 'Bastl G.',
 'Al-Alawi S.K.',
 'Caratti C.',
 'Arazi H.',
 'El Aynaoui Y.',
 'Luxa P.',
 'Kiefer N.',
 'Puerta M.',
 'Santoro F.',
 'Diaz J.',
 'Schuettler R.',
 'Siemerink J.',
 'Tillstrom M.',
 'Vicente F.',
 'Gaudio G.',
 'Marin J.A.',
 'Squillari F.',
 'Cherkasov A.',
 'Schalken S.',
 'Mirnyi M.',
 'Chang M.',
 'Federer R.',
 'Gambill J.M.',
 'Sargsian S.',
 'Gustafsson M.',
 'Tarango J.',
 'Johansson T.',
 'Berasategui A.',
 'Bjorkman J.',
 'Rosset M.',
 'Ivanisevic G.',
 'Sell M.',
 'Woodruff C.',
 'Ferrero J.C.',
 'Novak J.',
 'Kuerten G.',
 'Hrbaty D.',
 'Costa A.',
 'Koubek S.',
 'Lapentti N.',
 'Safin M.',
 'Martin T.',
 'Vacek D.',
 'Spadea V.',
 'Corretja A.',
 'Ilie A.',
 'Voinea A.',
 'Ljubicic I.',
 'Alami K.',
 'Alonso J.',
 'Black W.',
 'Boutter J.',
 'Dupuis A.',
 'Parmar A.',
 'Ferreira W.',
 'Motomura G.',
 'Haas T.',
 'Karbacher B.',
 'Kafelnikov Y.',
 'Canas G.',
 'Medvedev A.',
 'Llodra M.',
 'Black B.',
 'Mamiit C.',
 'Philippoussis M.',
 "O'Brien A.",
 'Sampras P.',
 'Blanco G.',
 'Sluiter R.',
 'Sirianni J.',
 'Srichaphan P.',
 'Tieleman L.',
 'Lareau S.',
 'Ullyett K.',
 'Stanoytchev O.',
 'Woodbridge T.',
 'Mantilla F.',
 'Agassi A.',
 'Hill M.',
 'Portas A.',
 'Burgsmuller L.',
 'Gross O.',
 'Prinosil D.',
 'Pavel A.',
 'Raoux G.',
 'Courier J.',
 'Salzenstein J.',
 'Gimelstob J.',
 'Blake J.',
 'Gumy H.',
 'Rodriguez M.',
 'Liukko V.',
 'Woodforde M.',
 'Massu N.',
 'Larsson M.',
 'MacPhie B.',
 'Jensen L.',
 'Pretzsch A.',
 'Popp A.',
 'Reneberg R.',
 'Sa A.',
 'Dewulf F.',
 'Kucera K.',
 'Wessels P.',
 'Rusedski G.',
 'Saulnier C.',
 'Zabaleta M.',
 'Chela J.I.',
 'Etlis G.',
 'Bruguera S.',
 'Viloca J.A.',
 'di Pasquale A.',
 'Heuberger I.',
 'Bryan M.',
 'Clavet F.',
 'Stark J.',
 'Hipfl M.',
 'van Lottum J.',
 'Roddick A.',
 'Rafter P.',
 'Malisse X.',
 'Calatrava A.',
 'Calleri A.',
 'Ulihrach B.',
 'Alvarez E.',
 'Hood M.',
 'Gonzalez P.',
 'Hadad M.',
 'Prieto S.',
 'Ondruska M.',
 'Meligeni F.',
 'Moya C.',
 'Rios M.',
 'Dent T.',
 'Nalbandian D.',
 'Ruud C.',
 'Kratochvil M.',
 'Fish M.',
 'Kim K.',
 'Harper-Griffith L.',
 'Huet S.',
 'Taino E.',
 'Stoliarov A.',
 'Lopez-Moron A.',
 'Willems R.',
 'Guardiola T.',
 'Coutelot N.',
 'Mota B.',
 'Marques N.',
 'Burrieza O.',
 'Lopez F.',
 'Gaudenzi A.',
 'Krajicek R.',
 'Navarro S.',
 'Puentes G.',
 'Coria G.',
 'Browne F.',
 'Delgado R.',
 'Russell M.',
 'Gonzalez F.',
 'Goellner M.K.',
 'Kohlmann M.',
 'Humphries S.',
 'Giner J.',
 'Charpentier M.',
 'Eschauer W.',
 'Mahut N.',
 'Serrano O.',
 'Savolt A.',
 'Trifu G.',
 'Bryan B.',
 'Cowan B.',
 'Wheaton D.',
 'Nestor D.',
 'Lee M.',
 'Landsberg J.',
 'Boruszewski J.',
 'van Scheppingen D.',
 'Youzhny M.',
 'Gaudi I.',
 'Bower J.',
 'Levy H.',
 'Rochus O.',
 'Voltchkov V.',
 'Timfjord N.',
 'Fleischfresser T.',
 'Thomann N.',
 'Godwin N.',
 'Morrison J.',
 'Garcia A.',
 'Kempes E.',
 'Filippini M.',
 'Roitman S.',
 'Davydenko N.',
 'Hernych J.',
 'Elsner D.',
 'Zovko L.',
 'Vajda I.',
 'Sanchez D.',
 'Martelli M.',
 'Schranz W.',
 'Carretero R.',
 'Moretti H.',
 'Fasching A.',
 'Luzzi F.',
 'Cabello F.',
 'Costa F.',
 'Mathieu P.H.',
 'Roux L.',
 'Malcor O.',
 'Larose S.',
 'King P.',
 'Washington M.',
 'Caldwell D.',
 'Capalik K.',
 'Kim A.',
 'Kralert P.',
 'Lee H.T.',
 'Moldovan I.',
 'Sabau R.',
 'Pescariu D.',
 'Erlich J.',
 'Nargiso D.',
 'Tarallo S.',
 'Tong M.',
 'Galimberti G.',
 'Flygt K.',
 'Iwabuchi S.',
 'Suzuki T.',
 'Onoda M.',
 'Friedl L.',
 'Zhu B.Q.',
 'Robredo T.',
 'Pless K.',
 'Phau B.',
 'Bachelot J.F',
 'Palmer J.',
 'Childs L.',
 'Furlan R.',
 'Froberg J.',
 'Sarstrand M.',
 'Ortegren J.',
 'Jones A.',
 'Bhupathi M.',
 'Weiner G.',
 'Schukin Y.',
 'Fukarek O.',
 'Horna L.',
 'Simoni A.',
 'Tobon M.',
 'Hirigoyen I.',
 'Behr N.',
 'Settergren J.',
 'Arquez P.',
 'Acasuso J.',
 'Tursunov D.',
 'Hernandez A.',
 'Eagle J.',
 'Saretta F.',
 'Vemic D.',
 'Ginepri R.',
 'Belal C.',
 'Vacek J.',
 'Couto E.',
 'Sousa T.',
 'Montanes A.',
 'Labadze I.',
 'Wassen R.',
 'Melo D.',
 'Traykov I.',
 'Andersen J.F.',
 'Galvani S.',
 'Kauffmann C.',
 'Okun N.',
 'Carlsen K.',
 'Allegro Y.',
 'Elseneer G.',
 'Hilton M.',
 'Yoon Y.',
 'Knowle J.',
 'Vlasov D.',
 'Radic M.',
 'Norman D.',
 'Mutis O.',
 'Lopez M.',
 'Herm-Zahlava J.',
 'Bozic I.',
 'Kutsenko V.',
 'Schiessling T.',
 'Marach O.',
 'Armando H.',
 'Pfeiffer K.',
 'Stepanek R.',
 'Fleishman Z.',
 'Harsanyi P.',
 'Joyce M.',
 'Peya A.',
 'Bogomolov Jr.A.',
 'Brasington J.',
 'Ramirez Hidalgo R.',
 'Alves T.',
 'Mello R.',
 'Oncins J.',
 'Ogorodov O.',
 'Karlovic I.',
 'Jiang S.',
 'Wang Y.',
 'Terachi T.',
 'Hui J.',
 'Garcia-Sintes J.',
 'Volandri F.',
 'Zimonjic N.',
 'Kondo H.',
 'Thomas J.',
 'Udomchoke D.',
 'Benneteau J.',
 'Melzer J.',
 'Elgin M.',
 'Nieminen J.',
 'Soderling R.',
 'Dupre T.',
 'Reid T.',
 'Larkham T.',
 'Patience O.',
 'Carraz G.',
 'Ascione T.',
 'Silva J.',
 'Massa E.',
 'Bahrouzyan O.',
 'Mazarakis V.',
 'Verkerk M.',
 'Ancic M.',
 'El Aarej M.',
 'Matias N.',
 'Ferrer D.',
 'Gasquet R.',
 'Krajan Z.',
 'Marin L.',
 'Nadal-Parera R.',
 'Kohlschreiber P.',
 'de Chaunac S.',
 'Hadad A.',
 'Perez D.',
 'Vassallo-Arguello M.',
 'Miranda I.',
 'Dreekmann H.',
 'Bogdanovic A.',
 'Moodie W.',
 'Muller G.',
 'Ivanov-Smolensky K.',
 'Cadart R.',
 'Mackin A.',
 'Waske A.',
 'Vahaly B.',
 'Prpic F.',
 'Fraile G.',
 'Hanescu V.',
 'Todero N.',
 'Blake T.',
 'Ellwood B.',
 'Dancevic F.',
 'Agaev E.',
 'Boeker M.',
 'Saoudi S.',
 'Kunitcin I.',
 'Craca M.',
 'Abel M.',
 'Shvec A.',
 'Johansson J.',
 'Beck K.',
 'Vliegen K.',
 'Bopanna R.',
 'Lisnard J.R.',
 'Varlet J.',
 'Amritraj P.',
 'Van Lottum J.',
 'Rea S.',
 'Luczak P.',
 'Crabb J.',
 'Bogomolov Jr. A.',
 'Gambill J. M.',
 'Gamonal H.',
 'Peralta J.',
 'Daniel M.',
 'Prodon E.',
 'Baker B.',
 'Marin J.A',
 'Di Pasquale A.',
 'Kendrick R.',
 'Gooding J.',
 'Lapentti G.',
 'Verdasco F.',
 'Tahiri M.',
 'Lopes H.',
 'Nadal R.',
 'Cermak F.',
 'Garcia-Lopez G.',
 'Kunitsyn I.',
 'Mathieu P.',
 'Schuettler P.',
 'Scherrer J.C.',
 'de Voest R.',
 'Moser F.',
 'Hemmes F.',
 'Petzschner P.',
 'Baccanello P.',
 'Mertinak M.',
 'Bloomfield R.',
 'Niemeyer F.',
 'Rehnquist B.',
 'Lammer M.',
 'Guccione C.',
 'Hernandez O.',
 'Levinsky J.',
 'Wawrinka S.',
 'Starace P.',
 'Levine I.',
 'Behrmann M.',
 'Reynolds B.',
 'Delic A.',
 'Ayala D.',
 'Neumuller I.',
 'Vik R.',
 'Koellerer D.',
 'Karanusic R.',
 'Tuksar S.',
 'Yim R.',
 'Golovanov D.',
 'Matkowski M.',
 'Dabrowski B.',
 'MacLagan M.',
 'Youzhny A.',
 'Ramirez-Hidalgo R.',
 'Berdych T.',
 'Capdeville P.',
 'Moraru G.',
 'Chiudinelli M.',
 'Ratiwatana S.',
 'di Mauro A.',
 'Veronelli D.',
 'Tenconi T.',
 'Andreev I.',
 'Aldi F.',
 'Almagro N.',
 'Iwami T.',
 'Scherrer J.',
 'Ferrero J.',
 'Mankad H.',
 'Rastogi K.',
 'Khalfan S.',
 'Kucera V.',
 'Bogomolov A.',
 'Santopadre V.',
 'Seppi A.',
 'Bracciali D.',
 'Bohli S.',
 'Hippensteel K.',
 'Monaco J.',
 'Cakl T.',
 'Mayer F.',
 'Gallardo M.',
 "Dell'Acqua M.",
 'Marcaccio G.',
 'Tavares L.',
 'Robert S.',
 'Devilder N.',
 'Pashanski B.',
 'Kindlmann D.',
 'Pescosolido S.',
 'Vagnozzi S.',
 'Ventura S.',
 'Serra F.',
 'Jeanpierre J.',
 'Tipsarevic J.',
 'Haehnel J.',
 'Falla A.',
 'Marray J.',
 'Flanagan I.',
 'Ancic I.',
 'Fitz S.',
 'Navarro-Pastor I.',
 'Lu Y.H.',
 'Hellstrom M.',
 'Gabashvili T.',
 'Verdasco M.',
 'Eleskovic E.',
 'van Gemerden M.',
 'Przysiezny M.',
 'Cook L.',
 'Guzman J.P.',
 'Beck A.',
 'Ram R.',
 'Ager J.',
 'Minar I.',
 'Djokovic N.',
 'Urban F.',
 'Kubot L.',
 'Baghdatis M.',
 'Jenkins S.',
 'Benneteau A.',
 'Odesnik W.',
 'Healey N.',
 'Tsonga J.W.',
 'Lu H.',
 'Ionita V.',
 'Bohane A.',
 'Widom T.',
 'Gimeno-Traver D.',
 'Zeng S.X.',
 'Roger-Vasselin E.',
 'Simon G.',
 'Gicquel M.',
 'Monfils G.',
 'Stakhovsky S.',
 'Ryderstedt M.',
 'Nielsen M.',
 'Bourgeois L.',
 'Kimmich M.',
 'Nunez E.',
 'Sun P.',
 'Vico U.',
 'Parada F.',
 'Wang Y.T.',
 'Dailey Z.',
 'Minar J.',
 'Tecau H.',
 'Evans B.',
 'Berrer M.',
 'Machado R.',
 'Sela D.',
 'Dlouhy L.',
 'Murray A.',
 'Klein T.',
 'Goodall J.',
 'Sherwood D.',
 'Summerer T.',
 'Oudsema S.',
 'Wilson B.',
 'Mergea F.',
 'Korteling S.',
 'Lu Y.',
 'Brzezicki J.P.',
 'Thron A.',
 'Bozoljac I.',
 'Fyrstenberg M.',
 'Chadaj A.',
 'Smeets R.',
 'Clayton A.',
 'Bester P.',
 'Young D.',
 'Gregorc L.',
 'Matsui T.',
 'Wang Y. Jr',
 'Gremelmayr D.',
 'Chen T.',
 'Do M.Q.',
 'Greul S.',
 'Naso G.',
 'Sanchez de Luna J.A.',
 'Fognini F.',
 'Ittogi T.',
 'Soeda G.',
 'Ledovskikh M.',
 'Davletshin V.',
 'Junaid R.',
 'King-Turner D.',
 'Berlocq C.',
 'Snobel P.',
 'Faurel J.C.',
 'Del Potro J.M.',
 'Aguilar J.',
 'Cuadrado C.',
 'Cilic M.',
 'Korolev E.',
 'Querry S.',
 'Rettenmaier T.',
 'Warburg S.',
 'Ghem A.',
 'Van der Dium A.',
 'Gallardo Valles M.',
 'Kuznetsov A.',
 'Burniol G.',
 'Balleret B.',
 'Klec I.',
 'Salva B.',
 'Ouahab L.',
 'Peric T.',
 'Gil F.',
 'Chela J.',
 'Popp T.',
 'Hartfield D.',
 'Chardy J.',
 'Montcourt M.',
 'Baker J.',
 'Haase R.',
 'Qureshi A.',
 'Zverev M.',
 'Becker B.',
 'Al Ghareeb M.',
 'Kutac R.',
 'Whitehouse W.',
 'Sijsling I.',
 'Darcis S.',
 'De Bakker T.',
 'Gonzalez S.',
 'Querrey S.',
 'Rieschick S.',
 'Junqueira D.',
 'Patriarca D.',
 'Sandbichler A.',
 'Azzaro L.',
 'Haider-Mauer A.',
 'Cipolla F.',
 'Ianni S.',
 'Sweeting R.',
 'Stoppini A.',
 'Polansky P.',
 'Hajek J.',
 'Simmonds P.',
 'Dolgopolov A.',
 'Crivoi V.',
 'Economidis K.',
 ' Hajek J.',
 'Clemens T.',
 'Chaen T.',
 'Troicki V.',
 'Istomin D.',
 'Fish A.',
 'Eitzinger R.',
 'Reister J.',
 'Gulbis E.',
 'Robredo R.',
 'Jun W.',
 'Levine J.',
 'Schwank E.',
 'Huta Galung J.',
 'Witten J.',
 'Bolelli S.',
 'Andujar P.',
 'Gensse A.',
 'Granollers M.',
 'Dustov F.',
 'Chaki R.',
 'Sousa P.',
 'Brands D.',
 'Bachinger M.',
 'Eysseric J.',
 'Recouderc L.',
 'Giraldo S.',
 'Tveit E.',
 'Isner J.',
 'Nishikori K.',
 'Lacko L.',
 'Fischer M.',
 'Gonzalez M.',
 'Riba P.',
 'Olejniczak D.',
 'Klizan M.',
 'Cuevas P.',
 'McClune M.',
 'Echagaray B.',
 'Yu X.Y.',
 'Gard C.',
 'Meffert D.',
 'Lindahl N.',
 'Stadler S.',
 'Singh N.',
 'Dev Varman S.',
 'Guez D.',
 'Nam H.W.',
 'Matsukevitch D.',
 'Golubev A.',
 'Chekov P.',
 'Kudryavtsev A.',
 'Dorsch B.',
 'Statham R.',
 'Rosol L.',
 'Slanar M.',
 'Podlipnik H.',
 'Marrero D.',
 'Munoz de la Nava D.',
 'Decoud S.',
 'Bowles C.',
 'Crugnola M.',
 'Bellucci T.',
 'Smyczek T.',
 'Skugor F.',
 'Kavcic B.',
 'Anderson K.',
 'Elias G.',
 'Harrison R.',
 'Kukushkin M.',
 'Marrai M.',
 'Trujillo G.',
 'Del Potro J.',
 'Sidorenko A.',
 'Fabbiano T.',
 'Sanchez De Luna J.',
 'Lopez-Jaen M.A.',
 'De Voest R.',
 'Berankis R.',
 'Dimitrov G.',
 'Ward J.',
 'Nielsen F.',
 'Slabinsky A.',
 'Groth S.',
 'Kamke T.',
 'Van der Merwe I.',
 'Eaton C.',
 'Goransson T.',
 'Ouanna J.',
 'Dabul B.',
 'Brizzi A.',
 'Jun W.S.',
 'Oswald P.',
 'Mayer L.',
 'Belic L.',
 'Yani M.',
 'Ignatik U.',
 'Ball C.',
 'Krajicek A.',
 'Cruciat A.',
 'Qureshi A.U.H.',
 'Xu J.C.',
 'Jouan R.',
 'Mannarino A.',
 'Ito Y.',
 'Ito T.',
 'Lejnieks K.',
 'Tomic B.',
 'Devvarman S.',
 'Statham J.',
 'Klein B.',
 'Klaasen R.',
 'Dodig I.',
 'Mektic N.',
 'Silva D.',
 'Munoz de La Nava D.',
 'Ferreiro F.',
 'Janowicz J.',
 'Riba-Madrid P.',
 'Hocevar R.',
 'Rufin G.',
 'Fleming C.',
 'Zemlja G.',
 'Zeballos H.',
 'Britton D.',
 'De Chaunac S.',
 'Agostinelli B.',
 'Ilhan M.',
 'Valent R.',
 'Marchenko I.',
 'Millot V.',
 'Vovk S.',
 'Luncanu P.A.',
 'Dolgopolov O.',
 'Haider-Maurer A.',
 'Karlovic I. ',
 'Seppi A. ',
 'Rochus O. ',
 'Stepanek R. ',
 'Luczak P. ',
 'Chiudinelli M. ',
 'Bolelli S. ',
 'Troicki V. ',
 'Beck A. ',
 'Nieminen J. ',
 'Koellerer D. ',
 'Cilic M. ',
 'Zeballos H. ',
 'Chardy J. ',
 'Ljubicic I. ',
 'Isner J. ',
 'Serra F. ',
 'Federer R. ',
 'Lammer M. ',
 'Korolev E. ',
 'Hernych J. ',
 'Wawrinka S. ',
 'Djokovic N. ',
 'Gasquet R. ',
 'Montanes A. ',
 'Mathieu P.H. ',
 'Garcia-Lopez G. ',
 'Falla A. ',
 'Simon G. ',
 'Granollers M. ',
 'Monaco J. ',
 'Almagro N. ',
 'Mayer L. ',
 'Ferrero J.C. ',
 'Murray A. ',
 'Rochus C. ',
 'Tipsarevic J. ',
 'Martin A. ',
 'Monfils G. ',
 'Youzhny M. ',
 'Robredo T. ',
 'Verdasco F. ',
 'Davydenko N. ',
 'Millman J.',
 'Ebden M.',
 'Yang T.H.',
 'Sorensen L.',
 'Lemke J.',
 'Cervantes I.',
 'Veic A.',
 'Lorenzi P.',
 'Brown D.',
 'Aranguren J.M.',
 'Saavedra Corvalan C.',
 'Souza J.',
 'Bemelmans R.',
 'Jelenic P.',
 'Poerschke L.',
 'Mertens Y.',
 'Matosevic M.',
 'Krajinovic F.',
 'El Amrani R.',
 'Niland C.',
 'Ramos-Vinolas A.',
 'Donskoy E.',
 'Gojowczyk P.',
 'Munoz-De La Nava D.',
 'Mina G.',
 'Emmrich M.',
 'Alcaide G.',
 'Kudla D.',
 'Marti Y.',
 'Velotti A.',
 'Johnson S.',
 'Melzer G.',
 'Raonic M.',
 'Duclos P.L.',
 'Paire B.',
 'Sock J.',
 'Copil M.',
 'Ungur A.',
 'Del Bonis F.',
 'Kravchuk K.',
 'Gong M.X.',
 'Bai Y.',
 'Bautista R.',
 'Sugita Y.',
 'Goffin D.',
 'Sabry S.',
 'Bubka S.',
 'Venus M.',
 'Scholtz N.',
 'Van Der Merwe I.',
 'Rios F.',
 'Pospisil J.',
 'Lajovic D.',
 'Clezar G.',
 'Dutra Silva R.',
 'Kuznetsov Al.',
 'Borvanov R.',
 'Schoorel T.',
 'Garza D.',
 'Awadhy O.',
 'Granollers Pujol G.',
 'Kuznetsov An.',
 'Ramos A.',
 'Sousa J.',
 'Teixeira M.',
 'Marti J.',
 'Golding O.',
 'Cox D.',
 'De Schepper K.',
 'Wang J.',
 'Lindell C.',
 'Olaso G.',
 'Cervenak P.',
 'Kern R.',
 'Stebe C.M.',
 'Knittel B.',
 'Kosakowski D.',
 'Thiem D.',
 'Muster T.',
 'Sitak A.',
 'Chvojka E.',
 'Pospisil V.',
 'Dasnieres de Veigy J.',
 'Jaziri M.',
 'Dutra Da Silva R.',
 'Giannessi A.',
 'Rodrigues M.',
 'Renavand N.',
 'Wu D.',
 'Li Z.',
 'Zhang Z.',
 'Zopp J.',
 'Duckworth J.',
 'Vardhan V.',
 'Bhambri Y.',
 'Viola Mat.',
 'Van D. Merwe I.',
 'Marcan D.',
 'Lajola D.',
 'Kutrovsky D.',
 'Bagnis F.',
 'Olivetti A.',
 'Cabal J.S.',
 'Djokovic M.',
 'Williams R.',
 'Delbonis F.',
 'Ziadi M.',
 'Idmbarek Y.',
 'Gutierrez-Ferrol S.',
 'Brugues-Davi A.',
 'Balazs A.',
 'Farah R.',
 'Menendez-Maceiras A.',
 'Bedene A.',
 'Trungelliti M.',
 'Ehrat S.',
 'Mcclune M.',
 'Klahn B.',
 'Novikov D.',
 'Reix C.',
 'Betov S.',
 'Fidirko N.',
 'Siriluethaiwattana P.',
 'Deen Heshaam A.',
 'Singh S.',
 'Rosenholm P.',
 'Laaksonen H.',
 'Mitchell B.',
 'Stebe C-M.',
 'Zayed M. S.',
 'Safwat M.',
 'Saville L.',
 'Pella G.',
 'Weintraub A.',
 'Pouille L.',
 'Alund M.',
 'Viola M.',
 'Veger F.',
 'Reyes-Varela M.A.',
 'Ramirez C.',
 'Schwartzman D.',
 'Rachidi Y.',
 'Carreno-Busta P.',
 'Granollers G.',
 'Carballes Baena R.',
 'Struff J.L.',
 'Krawietz K.',
 'Ghedin R.',
 'Basic M.',
 'Evans D.',
 'Edmund K.',
 'Ymer E.',
 'Pavic A.',
 'Bossel A.',
 'Salamanca C.',
 ...]

In [10]:
df['Player_1'].value_counts()

Player_1
Federer R.      668
Nadal R.        619
Djokovic N.     601
Ferrer D.       539
Gasquet R.      482
               ...
Spizzirri E.      1
Dodig M.          1
Boyer T.          1
Gea A.            1
Svajda T.         1
Name: count, Length: 1494, dtype: int64

## Sort in terms of date

In [11]:
df = df.sort_values("Date").reset_index(drop=True)
df

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,63,77,-1,-1,-1.00,-1.00,6-4 6-2
1,Qatar Open,2000-01-03,International,Outdoor,Hard,1st Round,3,El Aynaoui Y.,Dupuis A.,El Aynaoui Y.,33,78,-1,-1,-1.00,-1.00,4-6 6-3 6-2
2,Qatar Open,2000-01-03,International,Outdoor,Hard,1st Round,3,Arazi H.,Cherkasov A.,Cherkasov A.,35,206,-1,-1,-1.00,-1.00,2-6 4-6
3,Qatar Open,2000-01-03,International,Outdoor,Hard,1st Round,3,Caratti C.,Heuberger I.,Caratti C.,211,219,-1,-1,-1.00,-1.00,7-6 4-6 6-4
4,Qatar Open,2000-01-03,International,Outdoor,Hard,1st Round,3,Al-Alawi S.K.,Berasategui A.,Berasategui A.,-1,60,-1,-1,-1.00,-1.00,3-6 4-6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65699,Wimbledon,2025-07-09,Grand Slam,Outdoor,Grass,Quarterfinals,5,Shelton B.,Sinner J.,Sinner J.,10,1,3130,10430,3.60,1.25,6-7 4-6 4-6
65700,Wimbledon,2025-07-09,Grand Slam,Outdoor,Grass,Quarterfinals,5,Djokovic N.,Cobolli F.,Djokovic N.,6,24,4630,2035,1.10,7.00,6-7 6-2 7-5 6-4
65701,Wimbledon,2025-07-11,Grand Slam,Outdoor,Grass,Semifinals,5,Sinner J.,Djokovic N.,Sinner J.,1,6,10430,4630,1.40,2.80,6-3 6-3 6-4
65702,Wimbledon,2025-07-11,Grand Slam,Outdoor,Grass,Semifinals,5,Fritz T.,Alcaraz C.,Alcaraz C.,5,2,4635,9300,4.75,1.17,4-6 7-5 3-6 6-7
65703,Wimbledon,2025-07-13,Grand Slam,Outdoor,Grass,The Final,5,Alcaraz C.,Sinner J.,Sinner J.,2,1,9300,10430,2.00,1.83,6-4 4-6 4-6 4-6

In [13]:
import numpy as np

df['Loser'] = np.where(df['Winner'] == df['Player_1'], df['Player_2'], df['Player_1'])

In [14]:
from collections import defaultdict

def compute_elo(df, k=32, init_elo=1000, surface_col="Surface"):
    # returns df with winner_elo_pre, loser_elo_pre, elo_diff and also updates internals
    df = df.copy()
    # initialize
    elo = defaultdict(lambda: init_elo)
    elo_surface = defaultdict(lambda: defaultdict(lambda: init_elo))
    w_elo_pre, l_elo_pre, w_elo_surf_pre, l_elo_surf_pre = [], [], [], []

    for _, row in df.iterrows():
        w, l = row["Winner"], row["Loser"]
        surf = row.get(surface_col, None)

        # pre-match
        w_pre = elo[w]
        l_pre = elo[l]
        w_surf_pre = elo_surface[w][surf]
        l_surf_pre = elo_surface[l][surf]

        w_elo_pre.append(w_pre)
        l_elo_pre.append(l_pre)
        w_elo_surf_pre.append(w_surf_pre)
        l_elo_surf_pre.append(l_surf_pre)

        # expected
        exp_w = 1 / (1 + 10 ** ((l_pre - w_pre) / 400))
        exp_l = 1 - exp_w

        # update global
        elo[w] += k * (1 - exp_w)
        elo[l] += k * (0 - exp_l)

        # update surface
        exp_w_s = 1 / (1 + 10 ** ((l_surf_pre - w_surf_pre) / 400))
        elo_surface[w][surf] += k * (1 - exp_w_s)
        elo_surface[l][surf] += k * (0 - (1 - exp_w_s))

    df["winner_elo_pre"] = w_elo_pre
    df["loser_elo_pre"] = l_elo_pre
    df["elo_diff"] = df["winner_elo_pre"] - df["loser_elo_pre"]
    df["winner_elo_surf_pre"] = w_elo_surf_pre
    df["loser_elo_surf_pre"] = l_elo_surf_pre
    df["elo_surf_diff"] = df["winner_elo_surf_pre"] - df["loser_elo_surf_pre"]
    return df

In [15]:
df = compute_elo(df)
df

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,Odd_1,Odd_2,Score,Loser,winner_elo_pre,loser_elo_pre,elo_diff,winner_elo_surf_pre,loser_elo_surf_pre,elo_surf_diff
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,...,-1.00,-1.00,6-4 6-2,Ljubicic I.,1000.000000,1000.000000,0.000000,1000.000000,1000.000000,0.000000
1,Qatar Open,2000-01-03,International,Outdoor,Hard,1st Round,3,El Aynaoui Y.,Dupuis A.,El Aynaoui Y.,...,-1.00,-1.00,4-6 6-3 6-2,Dupuis A.,1000.000000,1000.000000,0.000000,1000.000000,1000.000000,0.000000
2,Qatar Open,2000-01-03,International,Outdoor,Hard,1st Round,3,Arazi H.,Cherkasov A.,Cherkasov A.,...,-1.00,-1.00,2-6 4-6,Arazi H.,1000.000000,1000.000000,0.000000,1000.000000,1000.000000,0.000000
3,Qatar Open,2000-01-03,International,Outdoor,Hard,1st Round,3,Caratti C.,Heuberger I.,Caratti C.,...,-1.00,-1.00,7-6 4-6 6-4,Heuberger I.,1000.000000,1000.000000,0.000000,1000.000000,1000.000000,0.000000
4,Qatar Open,2000-01-03,International,Outdoor,Hard,1st Round,3,Al-Alawi S.K.,Berasategui A.,Berasategui A.,...,-1.00,-1.00,3-6 4-6,Al-Alawi S.K.,1000.000000,1000.000000,0.000000,1000.000000,1000.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65699,Wimbledon,2025-07-09,Grand Slam,Outdoor,Grass,Quarterfinals,5,Shelton B.,Sinner J.,Sinner J.,...,3.60,1.25,6-7 4-6 4-6,Shelton B.,1691.017465,1264.772588,426.244877,1228.440677,1059.863706,168.576971
65700,Wimbledon,2025-07-09,Grand Slam,Outdoor,Grass,Quarterfinals,5,Djokovic N.,Cobolli F.,Djokovic N.,...,1.10,7.00,6-7 6-2 7-5 6-4,Cobolli F.,1540.551042,1278.720210,261.830832,1543.038510,1078.877952,464.160558
65701,Wimbledon,2025-07-11,Grand Slam,Outdoor,Grass,Semifinals,5,Sinner J.,Djokovic N.,Sinner J.,...,1.40,2.80,6-3 6-3 6-4,Djokovic N.,1693.550941,1546.354282,147.196659,1237.234257,1545.107329,-307.873072
65702,Wimbledon,2025-07-11,Grand Slam,Outdoor,Grass,Semifinals,5,Fritz T.,Alcaraz C.,Alcaraz C.,...,4.75,1.17,4-6 7-5 3-6 6-7,Fritz T.,1654.507996,1404.951397,249.556599,1369.430975,1272.395562,97.035413
65703,Wimbledon,2025-07-13,Grand Slam,Outdoor,Grass,The Final,5,Alcaraz C.,Sinner J.,Sinner J.,...,2.00,1.83,6-4 4-6 4-6 4-6,Alcaraz C.,1703.150711,1660.654496,42.496215,1264.585888,1381.075004,-116.489116

In [16]:
def add_h2h_feature(df):
    df = df.copy()
    h2h = defaultdict(lambda: defaultdict(int))
    h2h_pre = []

    for _, row in df.iterrows():
        w, l = row["Winner"], row["Loser"]

        # record value BEFORE match
        h2h_pre.append(h2h[w][l] - h2h[l][w])

        # update AFTER match
        h2h[w][l] += 1

    df["h2h_pre"] = h2h_pre
    return df

df = add_h2h_feature(df)

In [17]:
from collections import deque
def add_recent_form(df, N=10):
    df = df.copy()
    recent_form = defaultdict(lambda: deque(maxlen=N))
    form_pre = []

    for _, row in df.iterrows():
        w, l = row["Winner"], row["Loser"]

        # wins so far before match
        w_wins = sum(recent_form[w])
        l_wins = sum(recent_form[l])
        form_pre.append(w_wins - l_wins)

        # update after match
        recent_form[w].append(1)
        recent_form[l].append(0)

    df["recent_form_diff"] = form_pre
    return df

df = add_recent_form(df)

In [4]:
def make_training_rows(df):
    rows = []
    for _, row in df.iterrows():
        w, l = row["Winner"], row["Loser"]

        # features
        w_feats = {
            "elo_diff": row["winner_elo_pre"] - row["loser_elo_pre"],
            "elo_surf_diff": row["winner_elo_surf_pre"] - row["loser_elo_surf_pre"],
            "h2h_pre": row["h2h_pre"],
            "recent_form_diff": row["recent_form_diff"],
            "label": 1  # winner perspective
        }
        l_feats = {
            "elo_diff": row["loser_elo_pre"] - row["winner_elo_pre"],
            "elo_surf_diff": row["loser_elo_surf_pre"] - row["winner_elo_surf_pre"],
            "h2h_pre": -row["h2h_pre"],  # flip perspective
            "recent_form_diff": -row["recent_form_diff"],
            "label": 0  # loser perspective
        }

        rows.append(w_feats)
        rows.append(l_feats)

    return pd.DataFrame(rows)

In [21]:
df.to_parquet('df_final.parquet', engine='fastparquet')

In [1]:
import pandas as pd
df = pd.read_parquet('df_final.parquet')

In [2]:
cutoff_date = "2022-01-01"
train = df[df["Date"] < cutoff_date]
test = df[df["Date"] >= cutoff_date]

In [5]:
train_data = make_training_rows(train)
test_data = make_training_rows(test)

X_train = train_data.drop(columns=["label"])
y_train = train_data["label"]

X_test = test_data.drop(columns=["label"])
y_test = test_data["label"]

print(y_train.value_counts())  # should now show both 0 and 1

label
1    56410
0    56410
Name: count, dtype: int64

In [7]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

model = XGBClassifier(
    n_estimators=200, max_depth=6, learning_rate=0.05, eval_metric="logloss"
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6473531310522918

In [9]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42, max_depth=2)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6475683236496664

In [10]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.64      0.64      9294
           1       0.65      0.66      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

In [23]:
best_depth = 0
max_accuracy = 0

for depth in range(1, 10):
    model_depth = DecisionTreeClassifier(random_state=42, max_depth=depth)
    model_depth.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    if (accuracy_score(y_test, y_pred) > max_accuracy):
        max_accuracy = accuracy_score(y_test, y_pred)
        best_depth = depth

print(max_accuracy)
print(classification_report(y_test, y_pred))

0.6475683236496664
              precision    recall  f1-score   support

           0       0.65      0.64      0.64      9294
           1       0.65      0.66      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6505810200129115
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

In [25]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(max_depth=20, random_state=0)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6435872605982355
              precision    recall  f1-score   support

           0       0.64      0.64      0.64      9294
           1       0.64      0.64      0.64      9294

    accuracy                           0.64     18588
   macro avg       0.64      0.64      0.64     18588
weighted avg       0.64      0.64      0.64     18588

In [26]:
df.shape

(65704, 26)

In [27]:
from sklearn.ensemble import StackingClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import GradientBoostingClassifier

estimators = [
    ('rf', RandomForestClassifier(
                    n_estimators=100,
                    max_depth=10,
                    min_samples_split=5,
                    min_samples_leaf=2,
                    random_state=42
                )),
    ('linear-svc', LinearSVC(C=1.0, max_iter=10000, random_state=42)),
    ('boost', GradientBoostingClassifier(
                            n_estimators=200,
                            learning_rate=0.1,
                            max_depth=5,
                            random_state=42
                        ))
]

stacking_model = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
stacking_model.fit(X_train, y_train)

y_pred = stacking_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.6521411663438778

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

# Linear Models

### Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6505810200129115
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### SGDClassifier

In [16]:
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(),
                    SGDClassifier(max_iter=1000, tol=1e-3))
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6462233699160749
              precision    recall  f1-score   support

           0       0.63      0.71      0.67      9294
           1       0.67      0.58      0.62      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.64     18588
weighted avg       0.65      0.65      0.64     18588

### RidgeClassifier

In [31]:
from sklearn.linear_model import RidgeClassifier

model = RidgeClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6514417904024101
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### Perceptron

In [32]:
from sklearn.linear_model import Perceptron

model = Perceptron(tol=1e-3, random_state=0)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6491822681299764
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### PassiveAgressiveClassifier

In [33]:
from sklearn.linear_model import PassiveAggressiveClassifier

model = PassiveAggressiveClassifier(max_iter=1000, random_state=0, tol=1e-3)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6243813212825479
              precision    recall  f1-score   support

           0       0.62      0.63      0.63      9294
           1       0.63      0.62      0.62      9294

    accuracy                           0.62     18588
   macro avg       0.62      0.62      0.62     18588
weighted avg       0.62      0.62      0.62     18588

# Support Vector Machines

### SVC

In [17]:
from sklearn.svm import SVC

model = make_pipeline(StandardScaler(), SVC(gamma='auto'))
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6516031848504411
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### Linear SVC

In [28]:
from sklearn.svm import LinearSVC

model = make_pipeline(StandardScaler(),
                    LinearSVC(random_state=0, tol=1e-5))
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6518721755971595
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### NuSVC

In [36]:
from sklearn.svm import NuSVC

model = make_pipeline(StandardScaler(), NuSVC())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.5157090596083495
              precision    recall  f1-score   support

           0       0.52      0.49      0.50      9294
           1       0.51      0.54      0.53      9294

    accuracy                           0.52     18588
   macro avg       0.52      0.52      0.52     18588
weighted avg       0.52      0.52      0.52     18588

# Tree-Based Models & Ensembles

### Decision Tree

In [37]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=0)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.569829997848074
              precision    recall  f1-score   support

           0       0.57      0.58      0.57      9294
           1       0.57      0.56      0.57      9294

    accuracy                           0.57     18588
   macro avg       0.57      0.57      0.57     18588
weighted avg       0.57      0.57      0.57     18588

### ExtraTreeClassifier

In [38]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import ExtraTreeClassifier

extra_tree = ExtraTreeClassifier(random_state=0)
model = BaggingClassifier(extra_tree, random_state=0).fit(
   X_train, y_train)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6060899505057026
              precision    recall  f1-score   support

           0       0.59      0.66      0.63      9294
           1       0.62      0.55      0.58      9294

    accuracy                           0.61     18588
   macro avg       0.61      0.61      0.60     18588
weighted avg       0.61      0.61      0.60     18588

### RandomForestClassifier

In [39]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(max_depth=2, random_state=0)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6490208736819454
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### Gradient Boost Classifier

In [18]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
    max_depth=1, random_state=0).fit(X_train, y_train)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6513879922530665
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### HistGradientBoostingClassifier

In [41]:
from sklearn.ensemble import HistGradientBoostingClassifier

model = HistGradientBoostingClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6507424144609425
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### AdaBoostClassifier

In [42]:
from sklearn.ensemble import AdaBoostClassifier

model = AdaBoostClassifier(n_estimators=100, random_state=0)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6486980847858833
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

# Nearest Neighbors

### KNeighborsClassifier

In [44]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6131375080697224
              precision    recall  f1-score   support

           0       0.61      0.61      0.61      9294
           1       0.61      0.61      0.61      9294

    accuracy                           0.61     18588
   macro avg       0.61      0.61      0.61     18588
weighted avg       0.61      0.61      0.61     18588

# Naive Bayes

### GaussianNB

In [46]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6497202496234129
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### MultinomialNB

In [54]:
from sklearn.naive_bayes import MultinomialNB

X_train_non_negative = np.abs(X_train)

model = MultinomialNB()
model.fit(X_train_non_negative, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.5
              precision    recall  f1-score   support

           0       0.50      1.00      0.67      9294
           1       0.00      0.00      0.00      9294

    accuracy                           0.50     18588
   macro avg       0.25      0.50      0.33     18588
weighted avg       0.25      0.50      0.33     18588

/home/souparno/Documents/tennis-prediction/tennis-env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/souparno/Documents/tennis-prediction/tennis-env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/souparno/Documents/tennis-prediction/tennis-env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### BernoulliNB

In [48]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.64923606627932
              precision    recall  f1-score   support

           0       0.65      0.66      0.65      9294
           1       0.65      0.64      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

# Discriminant Analysis

### LinearDiscriminantAnalysis

In [19]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
model = LinearDiscriminantAnalysis()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6514417904024101
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

### QuadraticDiscriminantAnalysis

In [52]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
model = QuadraticDiscriminantAnalysis()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6514417904024101
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

# Neural Network Models

### MLPClassifier

In [53]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6506348181622552
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

# LightBGM

In [11]:
import lightgbm as lgb
model = lgb.LGBMClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[LightGBM] [Info] Number of positive: 56410, number of negative: 56410
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000396 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 569
[LightGBM] [Info] Number of data points in the train set: 112820, number of used features: 4
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
Accuracy: 0.6495050570260383
              precision    recall  f1-score   support

           0       0.65      0.65      0.65      9294
           1       0.65      0.65      0.65      9294

    accuracy                           0.65     18588
   macro avg       0.65      0.65      0.65     18588
weighted avg       0.65      0.65      0.65     18588

# Voting Classifier

In [20]:
from sklearn.ensemble import VotingClassifier

ensemble = VotingClassifier(
    estimators=[
        ('logreg', LogisticRegression(max_iter=1000)),
        ('svc', SVC(probability=True)),
        ('xgb', XGBClassifier(eval_metric="logloss")),
        ('gb', GradientBoostingClassifier()),
        ('lda', LinearDiscriminantAnalysis())
    ],
    voting='soft'  # soft = uses probabilities, better than hard
)
ensemble.fit(X_train, y_train)
print("Ensemble accuracy:", ensemble.score(X_test, y_test))

Ensemble accuracy: 0.6515493867010975

# Stacking Classifier

In [21]:
from sklearn.ensemble import StackingClassifier

stack = StackingClassifier(
    estimators=[
        ('logreg', LogisticRegression(max_iter=1000)),
        ('svc', SVC(probability=True)),
        ('xgb', XGBClassifier(eval_metric="logloss")),
        ('gb', GradientBoostingClassifier()),
    ],
    final_estimator=LogisticRegression(max_iter=1000)  # meta-learner
)
stack.fit(X_train, y_train)
print("Stacking accuracy:", stack.score(X_test, y_test))

Stacking accuracy: 0.6528405422853454

# Bagging

In [23]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bagging = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,       # number of trees
    max_samples=0.8,        # fraction of samples per estimator
    random_state=42
)
bagging.fit(X_train, y_train)
print("Bagging accuracy:", bagging.score(X_test, y_test))

Bagging accuracy: 0.6191629007962126

# Boosting

In [24]:
from sklearn.ensemble import AdaBoostClassifier

adaboost = AdaBoostClassifier(
    n_estimators=200,
    learning_rate=0.05,
    random_state=42
)
adaboost.fit(X_train, y_train)
print("AdaBoost accuracy:", adaboost.score(X_test, y_test))

AdaBoost accuracy: 0.6496664514740693

In [25]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)
gb.fit(X_train, y_train)
print("GradientBoost accuracy:", gb.score(X_test, y_test))

GradientBoost accuracy: 0.6510114052076609

In [26]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss"
)
xgb.fit(X_train, y_train)
print("XGBoost accuracy:", xgb.score(X_test, y_test))

XGBoost accuracy: 0.6490208736819454